language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -U pip
  - pip install -r dev-requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hP2foSJZUUDycBd0SxyUYoDuicYDFI6zKKWtQ3iq1lHvZBBZEyKvdB7WoPtgVbjdiqQeKB9yCx2Q4DUi7I1NXUprwewM3+SMGxVdr6v/8IEij/8a9M3Oe4vRDe87FTkYp0RO9MfjYcsNQD2wJ+HuxYQKYt+SCKW6XILYlS/57/lVovZze9Fd4JTCw6veNg8zClkTokJlVfTGQu5yi+7zDsmU2g8qLyx0r6zr0b22iGSDrjcMWaz2yuvog7JzL245Eiuq7ZOKlZd2YZWMUxLstv5vg50HR9MnXRZ8L+pAupjRL9iUYAyt+k84tsKg+xcfU6pvAFkLkJj3H1l9pAG0eY7r7sLSfPyEZq+s+MbvJ78yyz55F+pIcOD3OTKF2yfxj+3XBhYIqQeGshREMV++HKMlIgmOW3yzqV44Xgt8wcylYvJo712V49DAlImC10WhvoP/06Lxou93LnYuob6h6T9eVr/t45be5VBSJ1f8bYol3e6mxsj5NApRk6e59LdhwMoQTZbctARc+ZhNTpHP3QNQlyIo9vKWy5fyIqVdTklThqrEZVDkG+1FZDX7vT5T3I7zRJg/YbyxlXDq8MQlpISGhSBMRauZ0Art/TrYMpjOCC5vjNUez4n4bkZx5qNdmCxI7UdvzmZUwTVZcJBN9vxjCsoMb8r7iOlDVmJ66aY=
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.9
after_script:
  - echo "Deploy to PyPI finished."
